# Generated by Django 5.2.6 on 2025-10-12 19:34

import authsystem.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_remove_profile_user_rename_fullname_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authsystem.models.UserManager()),
            ],
        ),
    ]
