# Generated by Django 5.2.6 on 2025-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed_model',
            field=models.CharField(blank=True, choices=[('go', 'go'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20, null=True),
        ),
    ]
