# Generated by Django 5.2.6 on 2025-10-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBot',
            new_name='Chat',
        ),
    ]
