# Generated by Django 5.2.6 on 2025-10-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_chatbot_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bot_text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
